# Generated by Django 4.2.11 on 2026-04-25 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('content', models.TextField(verbose_name='content')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='tutorials/videos/', verbose_name='video file')),
                ('video_url', models.URLField(blank=True, verbose_name='video URL')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tutorials', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='departments.department', verbose_name='department')),
            ],
            options={
                'verbose_name': 'tutorial',
                'verbose_name_plural': 'tutorials',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='TutorialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tutorials/images/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='knowledgebase.tutorial', verbose_name='tutorial')),
            ],
            options={
                'verbose_name': 'tutorial image',
                'verbose_name_plural': 'tutorial images',
            },
        ),
        migrations.CreateModel(
            name='ReadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='read at')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_history', to='knowledgebase.tutorial', verbose_name='tutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_history', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'read history',
                'verbose_name_plural': 'read history',
                'ordering': ('-read_at',),
            },
        ),
    ]
