# Generated by Django 4.2.11 on 2026-04-25 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='video_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='video caption'),
        ),
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='video URL')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='knowledgebase.tutorial', verbose_name='tutorial')),
            ],
            options={
                'verbose_name': 'tutorial video',
                'verbose_name_plural': 'tutorial videos',
            },
        ),
    ]
