# Generated by Django 4.2.11 on 2026-04-25 18:07

from django.db import migrations, models


def deduplicate_readhistory(apps, schema_editor):
    ReadHistory = apps.get_model("knowledgebase", "ReadHistory")
    duplicated_pairs = (
        ReadHistory.objects.values("user_id", "tutorial_id")
        .annotate(row_count=models.Count("id"))
        .filter(row_count__gt=1)
    )
    for pair in duplicated_pairs:
        rows = ReadHistory.objects.filter(
            user_id=pair["user_id"],
            tutorial_id=pair["tutorial_id"],
        ).order_by("-read_at", "-id")
        keep = rows.first()
        rows.exclude(pk=keep.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0002_tutorial_video_caption_tutorialvideo'),
    ]

    operations = [
        migrations.RunPython(deduplicate_readhistory, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='readhistory',
            constraint=models.UniqueConstraint(fields=('user', 'tutorial'), name='unique_readhistory_user_tutorial'),
        ),
    ]
